import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul className="flex justify-end">
            <li>
              <a
                href={process.env.NEXT_PUBLIC_LOGOUT_URL}
                className="p-4 rounded-md bg-slate-500 cursor-pointer"
              >
                Logout
              </a>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
